### ISSUE TITLE
Repository Name 오타 수정

### ISSUE THREAD

**Issue by harrydrippin** [KMU-OSS-Laboratory/Open-Source-in-the-Enterprise#48]
현재 Repository Name에 오타가 있는 것 같습니다.

현재 : `Open-Source-in-the-Enteprise`
정상 : `Open-Source-in-the-Ente`**`r`**`prise`

바로 이름을 수정하면 현재 번역을 진행 중이신 분들의 Git Origin 주소가 바뀌어 혼란이 생길까 하여 Issue로 알려드립니다.

**Comment by minsuklee** [comment]
수정 했습니다. 예전, git origin 주소도 일단은 잘 동작하는 것같네요..
